name: timetrack
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider : 6.1.4
  intl : 0.20.2
  http : 1.3.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  one_clock: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/truck_logo.png
  uses-material-design: true




